Fix a bug in servicebus namespace private endpoint
This fixes a bug when creating a private endpoint for servicebus namespace. The wrong variable type is passed (base_tags) to the private endpoint module, example of error you can get:

```
Error: Invalid value for input variable
│
│   on ../aztfmod/modules/messaging/servicebus/namespace/private_endpoints.tf line 5, in module "private_endpoint":
│    5:   base_tags       = local.base_tags
│
│ The given value is not suitable for module.solution.module.servicebus_namespaces["sb1"].module.private_endpoint["pe1"].var.base_tags declared at
│ ../aztfmod/modules/networking/private_endpoint/variables.tf:27,1-21: bool required.
```

PENG-2502